### ISSUE TITLE
prometheus config 

### ISSUE THREAD

**Issue by robotneo** [G-PORTAL/redfish_exporter#7]
- job_name: "redfish-exporter"
    metrics_path: /redfish
    static_configs:
    - targets:
       - 172.17.42.31
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.40.5:9096
        
 Why can't it be collected?

**Comment by BirknerAlex** [comment]
Hi!

It would be very helpful if you could provide us the logs from the exporter or the scrape error from your prometheus instance. But what I can see is the metrics_path in your config is wrong, it should be `/metrics`.

You can test the exporter when running also by curling:

```
curl "http://<exporter ip>:9096/metrics?host=https://<redfish ip>&password=<redfish password>&username=<redfish username>"
```

**Comment by BirknerAlex** [comment]
Please let me know if you still experience any issues.
